import React from "react";
import Head from "next/head";
import First from "../components/first/First";
import Second from "../components/second/Second";
import Third from "../components/third/Third";
import Fourth from "../components/fourth/Fourth";
import Footer from "../components/footer/Footer";
import hiscores from "osrs-json-hiscores";

export async function getStaticProps() {
  const stats = await hiscores.getStats("Huell");

  return {
    props: {
      stats,
    },
    revalidate: 10,
  };
}

export default function App({ stats }) {
  console.log(stats);
  return (
    <>
      <Head>
        <title>OSRS HiScore | {stats["name"]} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <div className="row">
            <div className="col-6 offset-3 p-5">
              <span>User checked: {stats["name"]}</span> <br />
              <span>
                Total XP: {stats["main"]["skills"]["overall"]["xp"]}
              </span>{" "}
              <br />
              <span>
                Vorkath kills: {stats["main"]["bosses"]["vorkath"]["score"]}
              </span>{" "}
              <br />
            </div>
          </div>
        </div>
        <First />
        <Second />
        <Third />
        <Fourth />
      </main>
      <Footer />
    </>
  );
}
