import React from "react";
import hiscores from "osrs-json-hiscores";
import { useRouter } from "next/router";
import Head from "next/head";
import Pvm from "../components/sections/Pvm";
import Skills from "../components/sections/Skills";
import Third from "../components/third/Third";
import Fourth from "../components/fourth/Fourth";
import Footer from "../components/footer/Footer";

let user = "Huell";
let pageTitle = `OSRS HiScore | ${user}`;

export async function getStaticProps() {
  const stats = await hiscores.getStats(user);
  return {
    props: {
      stats,
    },
    revalidate: 10,
  };
}

export default function App({ stats }) {
  let mode = stats.mode;
  let pvm = stats[mode]["bosses"];
  let skills = stats[mode]["skills"];

  console.log(stats);

  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-center text-md-start">
        <Skills obj={skills} />
        <Pvm obj={pvm} />
        <Third />
        <Fourth />
      </main>
      <Footer />
    </>
  );
}
